### ISSUE TITLE
License

### ISSUE THREAD

**Issue by finepointcgi** [abdullahnawazkhan/SpeechToText-Android-Godot#1]
Hey I noticed you have a really cool plugin here!

Could we get a license attached to it so we know what to expect? 

Im assuming its MIT or perhaps CCBY but a license would be useful for other developers so they know what they can and cannot do with your plugin. Im working on a tutorial to feature this plugin if it is MIT or CC.

**Comment by abdullahnawazkhan** [comment]
Hi! Thanks I forgot to add the license when uploading the project. I've added the license now

**Comment by finepointcgi** [comment]
Hey thanks,
Im doing a tutorial on android speech to text and this addon is one of the only ones that's still maintained! I put out a PR with some changes to add some features I felt would be useful.
